### ISSUE TITLE
Question: Set icons

### ISSUE THREAD

**Issue by otoomey** [Saeris/Scribe#1]
I have been reading through your code, and I can't figure out how you are getting the icon for each set. From what I can see, the MTG API does not expose icon URLs for card sets. Are you loading them from another source? Thanks in advance.

**Comment by Saeris** [comment]
Good question! I'll be sure to cover this in the docs once I get to writing more of them.

I'm actually using these two fantastic libraries on the front-end:

https://github.com/andrewgioia/Keyrune

https://github.com/andrewgioia/Mana

So where you see icons being added, right now all I'm doing is generating CSS class name snippets to be consumed later.

Hope that helps!
